### ISSUE TITLE
Fix `stylelint-config-recommended-less` failures due to pnpm workspace

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint-ecosystem-tester#27]
Currently, the `stylelint-config-recommended-less` tests have failed due to the following error:

```
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:^
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-07-29T00_38_55_514Z-debug-0.log
```

-- https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/10136082030/job/28024380422#step:8:10

This is because the current CI workflow doesn't support [pnpm workspaces](https://pnpm.io/workspaces);

```json
{
  "stylelint-less": "workspace:^"
}
```

-- https://github.com/stylelint-less/stylelint-less/blob/4d405e5b81a11efaeb83197a0300e1e9827cf401/packages/stylelint-config-recommended-less/package.json#L33

It would be great if we could resolve the failures.

**Comment by romainmenke** [comment]
Can we also make the package manager configurable, similar to : https://github.com/stylelint/stylelint-ecosystem-tester/issues/29#issuecomment-2257535373
