### ISSUE TITLE
Remove `stylelint-config-tailwindcss` due to missing `npm test`

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint-ecosystem-tester#28]
`stylelint-config-tailwindcss` doesn't have the `npm test` script, so the tests fail.

-- https://github.com/zhilidali/stylelint-config-tailwindcss/blob/c9703ae822dc285a642e1ae388f202affb52d590/package.json#L10-L12

```
npm error Missing script: "test"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2024-07-29T00_51_22_100Z-debug-0.log
```

-- https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/10136195215/job/28024646520#step:11:1

Should we recommend having `npm test` or skip `npm test` if a package doesn't have it?

**Comment by romainmenke** [comment]
If a package is popular and doesn't have any tests, then that is also some kind of failure.
Not something we can really help with, but definitely not a good situation.

Maybe the package was a minor side project and wasn't that mature, but suddenly gained some adoption?

I don't think we should include packages without tests in this project.

But maybewe need to reach out and let the maintainers know that their project doesn't have tests and suddenly has significant usage.

**Comment by ybiquitous** [comment]
Thanks for the feedback. 👍🏼 

Currently, [stylelint-config-tailwindcss](https://www.npmjs.com/package/stylelint-config-tailwindcss) is downloaded over than 18k,

<img width="380" alt="image" src="https://github.com/user-attachments/assets/4257e3ff-04d0-467b-a65a-e597bacab782">

And it's ranked in the top 20 config packages:

```
$ npm search --searchopts='sortBy=popularity' --searchlimit=20 'keywords:stylelint-config' stylelint-config-tailwindcss
stylelint-config-tailwindcss
tailwindcss shareable config for stylelinttailwindcss shareable config for stylelint
Version 0.0.7 published 2022-11-08 by zhilidali
Maintainers: zhilidali
Keywords: stylelint stylelint-config tailwindcss
https://npm.im/stylelint-config-tailwindcss
```

But I agree that not having tests is problematic.

Just removing the package from this repo seems easier because the package is so simple that it doesn't need tests.
