### ISSUE TITLE
Fix `@shopify/stylelint-plugin` failures due to missing `npm test`

### ISSUE THREAD

**Issue by ybiquitous** [stylelint/stylelint-ecosystem-tester#29]
Related to #28

Since `@shopify/stylelint-plugin` doesn't have a `npm test` script, the tests fail.
https://github.com/Shopify/web-configs/blob/fea6f31cacecf595f2f71ea11079e37bd82800dc/packages/stylelint-plugin/package.json

```
npm error Lifecycle script `test` failed with error:
npm error workspace @shopify/stylelint-plugin@14.0.0
npm error location /home/runner/work/stylelint-ecosystem-tester/stylelint-ecosystem-tester/packages/stylelint-plugin
npm error Missing script: "test"
```

-- https://github.com/stylelint/stylelint-ecosystem-tester/actions/runs/10136137903/job/28024512459#step:11:1

Should we recommend having `npm test` or skip `npm test` if a package doesn't have it?

**Comment by ybiquitous** [comment]
Providing an option to override the default command `npm test` may be good. For example:

https://github.com/stylelint/stylelint-ecosystem-tester/blob/da96d72799996a46c32cab0235b1ed5ab857598a/data/ecosystem.yml#L1

```yaml
packages:
  # Before
  - '@shopify/stylelint-plugin' # test-command defaults to 'npm test'
  
  # After
  - ['@shopify/stylelint-plugin', {test-command: 'npx jest'}]
```

**Comment by romainmenke** [comment]
I like this!
Then we aren't tied to a single convention.

**Comment by ybiquitous** [comment]
@romainmenke Feel free to implement the idea!　  👍
