### ISSUE TITLE
Should we use `--throw-deprecation`?

### ISSUE THREAD

**Issue by Mouvedia** [stylelint/stylelint-ecosystem-tester#38]
### What is the problem you're trying to solve?

Knowing which plugins/formatters/configs use deprecated features.

### What solution would you like to see?

Maybe consider the package status as failing when it throws using this flag?

ref https://nodejs.org/api/cli.html#--throw-deprecation

**Comment by romainmenke** [comment]
I don't think we should.
The intention is to catch unexpected breakage in the ecosystem.
