### ISSUE TITLE
Disable failing packages for now

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint-ecosystem-tester#39]
As mentioned in https://github.com/stylelint/stylelint-ecosystem-tester/pull/24, scheduled GitHub workflows ping the last editor of that workflow each time a run fails.

So my inbox each day looks like this 😅 

<img width="1205" alt="Screenshot 2024-08-19 at 10 41 11" src="https://github.com/user-attachments/assets/226073f5-f88a-447f-8487-10c6066d708d">

-------

The purpose of this repo is to find new and unexpected failures when we make changes in Stylelint itself.

Packages that are already failing arguably are not that interesting to track.

------

I propose that we comment out each failing package in `ecosystem.yml`.
While simultaneously opening a pull request for each to uncomment it again.

Each time such a PR turns green we can merge it.

**Comment by ybiquitous** [comment]
Oh, I agree with disabling them... Sorry for bothering you 🙇🏼 

Please feel free to do it! 🙏🏼

**Comment by romainmenke** [comment]
Thank you @ybiquitous 🙇 

Let's see how this approach goes.
I will try to prepare pull requests for each failing package and link those to upstream PR's or issues.

**Comment by Mouvedia** [comment]
`@wordpress/stylelint-config` has a [new release](https://www.npmjs.com/package/@wordpress/stylelint-config/v/23.0.1-next.1f6eadc42.0).

**Comment by ybiquitous** [comment]
Great. Can you open a PR to reenable it? If it passes CI, let's merge it!
