### ISSUE TITLE
Remove `stylelint-codeframe-formatter`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint-ecosystem-tester#46]
`stylelint-codeframe-formatter` doesn't have a test suite suitable for CI.

It does have a `test` command, but this always fails because that it runs Stylelint against a css file with errors.

The output is intended to be read by a person who can then determine if the package is behaving as intended.

Unless someone is willing to contribute a suitable test setup upstream I propose we remove it from our list.

---

see: https://github.com/stylelint/stylelint-ecosystem-tester/pull/45

**Comment by ybiquitous** [comment]
I agree with removing `stylelint-codeframe-formatter`. It looks no longer maintained.
