### ISSUE TITLE
Remove `stylelint-config-rational-order`

### ISSUE THREAD

**Issue by romainmenke** [stylelint/stylelint-ecosystem-tester#47]
Last update was 5 years ago: https://github.com/constverum/stylelint-config-rational-order

Questions about maintenance status from 4 years ago have been left unanswered: https://github.com/constverum/stylelint-config-rational-order/issues/38

I suggest removing it from our list.

**Comment by Mouvedia** [comment]
Let's add one config every time we remove one.
i.e. a config with is in top 20–30
e.g. [`stylelint-config-taro-rn`](https://github.com/NervJS/taro/tree/main/packages/stylelint-config-taro-rn)

**Comment by ybiquitous** [comment]
Sadly, I agree with removing [`stylelint-config-rational-order`](https://www.npmjs.com/package/stylelint-config-rational-order). It has still been downloaded more than 67,000 times weekly, but it's clearly unmaintained.
<img width="169" alt="image" src="https://github.com/user-attachments/assets/1a2ec8fa-669a-4021-9175-8d6dcb51888a">


> Let's add one config every time we remove one.

I don't think so, and we should consider it separately. If we want to add a new package, let's open a new issue.

**Comment by ybiquitous** [comment]
> let's open a new issue.

If an addition clearly makes sense, it's okay to directly open a pull request 😃
